name: Build and test back-end

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - run: pip3 install -r requirements.txt
        working-directory: packages/back

      - run: yarn --frozen-lockfile
        working-directory: packages/back

      - run: yarn build
        working-directory: packages/back

      - run: yarn test
        working-directory: packages/back

      - run: yarn lint:no-fix
        working-directory: packages/back

      - run: yarn doc
        working-directory: packages/back
